### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by mpconsultsai**
Suggestions:

optional arg for certificate accept - arg would be nothing if not required or y\n to accept cert

optional arg for group - arg would be nothing if not required, or 0\n for group 0, 1\n for group 1, etc.

### CODE REVIEW

**Comment by MarkTiedemann** [comment]
Hi Mark, could you please explain how this would work in more detail?

The referenced commit prefixes the username with a yes string and a group string `${yes}${group}${username}`, e.g. if I call the function with `username: 'mark'`, the resulting string would be `'yesgroupmark'`, which doesn't seem correct to me.

**Comment by mpconsultsai** [comment]
Thanks for the response.
That may be an error on the original authors implementation I assume this would require a \n - sorry missed that - If you have any additional input that would be great - I am unsure of the optional requirement for certificate accept  but assume anyconnect handles these in the file dependent on the number of parameters.

@mfahner-p any thoughts on this - thanks

**Comment by MarkTiedemann** [comment]
Okay, I see.

Unfortunately, I don't have AnyConnect installed, nor any servers I could connect to, so I cannot test this.

Can you add the missing `\n`, and test it?

Probably there should also not be any default value for these optional arguments.

I also find the `yes` parameter to be named rather generically. Might be better to name it `acceptCertificate` (and change the type to `boolean`).

**Comment by mpconsultsai** [comment]
Yep agree with your later point - I will make some changes and test it this week - and if successful will create a new PR - thanks for your input

**Comment by MarkTiedemann** [comment]
Thanks a lot, @MarkAPhillips!

PS: Would you be interested in helping to maintain this project?

**Comment by mpconsultsai** [comment]
@MarkTiedemann  possibly - let me review this tomorrow and create a PR once I have a working version. It is really a need a for my current requirement as need to connect via VPN for some automated API tests I am running in node.

**Comment by mfahnerpymnt** [comment]
I just made a new PR with the updates for cert/group as I'm currently using them.  I've tested for a couple different connections, both accepting the certificate, one using a group, one not using a group.

**Pull request closed without merging**
